### PR TITLE
Self contained dockercompose

### PR DESCRIPTION
**Pull request by saranrapjs**
Hi there!

I wanted to open this PR to show where we (NYT comments!) have arrived (so far) at with deploying a more ruggedized docker-compose setup for a single server install of coral.

- I'm using docker's container linking to expose connections between images (rather than via docker-generated environment variables, which are [deprecated](https://docs.docker.com/compose/link-env-deprecated/))
- I have a mongo image in there, using a volume that's *not* mapped to the host, for maximum portability. (I'll detail the changes we had to make to docker so we could have it run on external volumes so its internal volume could sprawl out on a larger mounted disk)
- I'm using docker-compose's [variable substitution support](https://docs.docker.com/compose/compose-file/#variable-substitution) to manage the main thing that requires change from host-to-host, which is the front-end http hostname

I'd love to hear what y'all think about these changes to the docker-compose file. I can also add README stuff to boot, if the direction here makes sense.

### CODE REVIEW

**Comment by gabelula** [comment]
Great! You just sent this PR on time as I'm writing a step-by-step guide on how to install Coral from the docker-compose for the hackaton. And I was having some problems that are resolved by your PR.  

I'm moving documentation from reef into a documentation repo and writing the guide and docker-compose.ytml there. 
cc  @edefikh

**Comment by gabelula** [comment]
Also, why are you using mongo image 3.0 instead of 3.2.3 that we had in the docker-compose?

**Comment by saranrapjs** [comment]
Definitely no particular reason for the 3.0 one 😄

**Comment by edefikh** [comment]
I adjusted our docker-compose.yml file to start utilizing variable substitution report. Its a great idea and it makes our yml file portable to any OS. I am also adjusting to start using docker's container linking to expose connections between images. 

Finally I have created a mongo seed functionality to our yml file so that it can setup auth and import sample data automatically. I will add the location to our new YML file as soon as I finish it.

**Comment by saranrapjs** [comment]
All sounds good — I'm assuming that all further work on `docker-compose.yml` file will be on the [docs repo version](https://github.com/coralproject/docs/blob/master/quickstart/compose.yml.sample)? 

I also might humbly request that there be a way of opting in/out of mongo seeding, if it's possible and not too rickety.  I can see us doing a lot of tweaking of how we import via sponge, less so tweaking of parameters within cay/pillar/xenia itself, where it'd be nice to start with a fresh/blank docker install.

**Comment by gabelula** [comment]
Yes. The updated version will be in the docs repo. 

Yes. Seeding as an option.

**Pull request merged**
